  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/jwt_security
      driver-class-name:  com.mysql.jdbc.Driver
      username: root
      password: w@2915djkq#
    jpa:
      hibernate:
        ddl-auto: create-drop
      show-sql: true
      properties:
        hibernate:
          format_sql: true
      database: mysql
      database-platform:  org.hibernate.dialect.MySQLDialect

